2018-03-12 12:29:31 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:29:31 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:29:33 ERROR EmployeeRepositoryJdbc:42 - Exception thrown while inserting new employee
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:40)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:99)
2018-03-12 12:30:27 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:30:27 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:30:28 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:100)
2018-03-12 12:30:44 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:30:44 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:42:42 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:42:42 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:42:44 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:122)
2018-03-12 12:42:44 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:42:44 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:42:45 ERROR EmployeeRepositoryJdbc:71 - Exception thrown while updating new employee
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.update(EmployeeRepositoryJdbc.java:69)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:42:56 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:42:56 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:42:57 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:122)
2018-03-12 12:42:57 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:42:57 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:42:58 ERROR EmployeeRepositoryJdbc:71 - Exception thrown while updating new employee
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.update(EmployeeRepositoryJdbc.java:69)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:44:58 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:44:58 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:45:01 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:122)
2018-03-12 12:45:01 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:45:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:45:04 TRACE EmployeeRepositoryJdbc:60 - UPDATE USER_T SET U_FIRST_NAME = ? U_LAST_NAME = ? U_USERNAME = ? U_PASSWORD = ? U_EMAIL = ? UR_ID = ?
2018-03-12 12:45:04 ERROR EmployeeRepositoryJdbc:71 - Exception thrown while updating new employee
java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.update(EmployeeRepositoryJdbc.java:69)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:45:30 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:45:30 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:45:32 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:122)
2018-03-12 12:45:32 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:45:32 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:45:33 TRACE EmployeeRepositoryJdbc:60 - UPDATE USER_T SET U_FIRST_NAME = ?, U_LAST_NAME = ?, U_USERNAME = ?, U_PASSWORD = ?, U_EMAIL = ?, UR_ID = ?
2018-03-12 12:45:33 ERROR EmployeeRepositoryJdbc:71 - Exception thrown while updating new employee
java.sql.SQLSyntaxErrorException: ORA-00904: "U_LAST_NAME": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.update(EmployeeRepositoryJdbc.java:69)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:45:59 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:45:59 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:46:00 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:122)
2018-03-12 12:46:00 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:46:00 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:46:00 TRACE EmployeeRepositoryJdbc:60 - UPDATE USER_T SET U_FIRSTNAME = ?, U_LASTNAME = ?, U_USERNAME = ?, U_PASSWORD = ?, U_EMAIL = ?, UR_ID = ?
2018-03-12 12:46:01 ERROR EmployeeRepositoryJdbc:71 - Exception thrown while updating new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.UNQ_USERNAME) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.update(EmployeeRepositoryJdbc.java:69)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:46:41 TRACE EmployeeRepositoryJdbc:27 - Inserting new employee
2018-03-12 12:46:41 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:46:42 ERROR EmployeeRepositoryJdbc:43 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:41)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:124)
2018-03-12 12:46:42 TRACE EmployeeRepositoryJdbc:50 - Inserting new employee
2018-03-12 12:46:42 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 12:46:42 TRACE EmployeeRepositoryJdbc:61 - UPDATE USER_T SET U_FIRSTNAME = ?, U_LASTNAME = ?, U_USERNAME = ?, U_PASSWORD = ?, U_EMAIL = ?, UR_ID = ? WHERE U_ID = ?
2018-03-12 13:01:05 TRACE EmployeeRepositoryJdbc:28 - Inserting new employee
2018-03-12 13:01:05 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:06 ERROR EmployeeRepositoryJdbc:44 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:42)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:155)
2018-03-12 13:01:06 TRACE EmployeeRepositoryJdbc:51 - Updating employee
2018-03-12 13:01:06 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:07 TRACE EmployeeRepositoryJdbc:82 - Selecting employee
2018-03-12 13:01:07 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:07 ERROR EmployeeRepositoryJdbc:110 - Exception thrown while selecting employee
java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3965)
	at oracle.jdbc.driver.InsensitiveScrollableResultSet.findColumn(InsensitiveScrollableResultSet.java:299)
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460)
	at com.revature.repository.EmployeeRepositoryJdbc.select(EmployeeRepositoryJdbc.java:102)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:158)
2018-03-12 13:01:27 TRACE EmployeeRepositoryJdbc:28 - Inserting new employee
2018-03-12 13:01:27 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:29 ERROR EmployeeRepositoryJdbc:44 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:42)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:155)
2018-03-12 13:01:29 TRACE EmployeeRepositoryJdbc:51 - Updating employee
2018-03-12 13:01:29 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:29 TRACE EmployeeRepositoryJdbc:82 - Selecting employee
2018-03-12 13:01:29 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:01:29 TRACE EmployeeRepositoryJdbc:158 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:02:12 TRACE EmployeeRepositoryJdbc:28 - Inserting new employee
2018-03-12 13:02:12 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:02:13 ERROR EmployeeRepositoryJdbc:44 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:42)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:154)
2018-03-12 13:02:13 TRACE EmployeeRepositoryJdbc:51 - Updating employee
2018-03-12 13:02:13 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:02:13 TRACE EmployeeRepositoryJdbc:82 - Selecting employee
2018-03-12 13:02:13 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:02:14 TRACE EmployeeRepositoryJdbc:157 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:06:26 TRACE EmployeeRepositoryJdbc:28 - Inserting new employee
2018-03-12 13:06:26 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:06:27 ERROR EmployeeRepositoryJdbc:44 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:42)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:182)
2018-03-12 13:06:27 TRACE EmployeeRepositoryJdbc:51 - Updating employee
2018-03-12 13:06:27 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:06:28 TRACE EmployeeRepositoryJdbc:82 - Selecting employee
2018-03-12 13:06:28 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:06:28 TRACE EmployeeRepositoryJdbc:185 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:06:28 TRACE EmployeeRepositoryJdbc:116 - Selecting employee
2018-03-12 13:06:28 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:06:29 TRACE EmployeeRepositoryJdbc:186 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:09:30 TRACE EmployeeRepositoryJdbc:29 - Inserting new employee
2018-03-12 13:09:30 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:09:31 ERROR EmployeeRepositoryJdbc:45 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:43)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:210)
2018-03-12 13:09:31 TRACE EmployeeRepositoryJdbc:52 - Updating employee
2018-03-12 13:09:31 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:09:31 TRACE EmployeeRepositoryJdbc:83 - Selecting employee
2018-03-12 13:09:31 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:09:31 TRACE EmployeeRepositoryJdbc:213 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:09:31 TRACE EmployeeRepositoryJdbc:117 - Selecting employee
2018-03-12 13:09:31 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:09:32 TRACE EmployeeRepositoryJdbc:214 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:09:32 TRACE EmployeeRepositoryJdbc:151 - Selecting employee
2018-03-12 13:09:32 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:09:32 TRACE EmployeeRepositoryJdbc:215 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=password1, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:12:00 TRACE EmployeeRepositoryJdbc:29 - Inserting new employee
2018-03-12 13:12:00 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:52 - Updating employee
2018-03-12 13:12:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:81 - Selecting employee
2018-03-12 13:12:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:211 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:115 - Selecting employee
2018-03-12 13:12:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:212 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:149 - Selecting employee
2018-03-12 13:12:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:12:01 TRACE EmployeeRepositoryJdbc:213 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:16:40 TRACE EmployeeRepositoryJdbc:29 - Inserting new employee
2018-03-12 13:16:40 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:41 ERROR EmployeeRepositoryJdbc:45 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:43)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:224)
2018-03-12 13:16:41 TRACE EmployeeRepositoryJdbc:52 - Updating employee
2018-03-12 13:16:41 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:42 TRACE EmployeeRepositoryJdbc:81 - Selecting employee
2018-03-12 13:16:42 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:43 TRACE EmployeeRepositoryJdbc:227 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:16:43 TRACE EmployeeRepositoryJdbc:115 - Selecting employee
2018-03-12 13:16:43 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:45 TRACE EmployeeRepositoryJdbc:228 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:16:45 TRACE EmployeeRepositoryJdbc:149 - Selecting all employees
2018-03-12 13:16:45 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:45 TRACE EmployeeRepositoryJdbc:229 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:16:45 TRACE EmployeeRepositoryJdbc:182 - Getting password hash
2018-03-12 13:16:45 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:16:45 TRACE EmployeeRepositoryJdbc:230 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:28:49 TRACE EmployeeRepositoryJdbc:31 - Inserting new employee
2018-03-12 13:28:49 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:51 ERROR EmployeeRepositoryJdbc:47 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:45)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:239)
2018-03-12 13:28:51 TRACE EmployeeRepositoryJdbc:54 - Updating employee
2018-03-12 13:28:51 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:53 TRACE EmployeeRepositoryJdbc:241 - true
2018-03-12 13:28:53 TRACE EmployeeRepositoryJdbc:83 - Selecting employee
2018-03-12 13:28:53 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:54 TRACE EmployeeRepositoryJdbc:242 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:28:54 TRACE EmployeeRepositoryJdbc:117 - Selecting employee
2018-03-12 13:28:54 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:55 TRACE EmployeeRepositoryJdbc:243 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:28:55 TRACE EmployeeRepositoryJdbc:151 - Selecting all employees
2018-03-12 13:28:55 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:55 TRACE EmployeeRepositoryJdbc:244 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:28:55 TRACE EmployeeRepositoryJdbc:184 - Getting password hash
2018-03-12 13:28:55 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:28:56 TRACE EmployeeRepositoryJdbc:245 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:28:56 TRACE EmployeeRepositoryJdbc:205 - Inserting new employee token
2018-03-12 13:28:56 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:41 TRACE EmployeeRepositoryJdbc:31 - Inserting new employee
2018-03-12 13:31:41 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:43 ERROR EmployeeRepositoryJdbc:47 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:45)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:239)
2018-03-12 13:31:43 TRACE EmployeeRepositoryJdbc:54 - Updating employee
2018-03-12 13:31:43 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:44 TRACE EmployeeRepositoryJdbc:241 - true
2018-03-12 13:31:44 TRACE EmployeeRepositoryJdbc:83 - Selecting employee
2018-03-12 13:31:44 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:45 TRACE EmployeeRepositoryJdbc:242 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:31:45 TRACE EmployeeRepositoryJdbc:117 - Selecting employee
2018-03-12 13:31:45 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:45 TRACE EmployeeRepositoryJdbc:243 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:31:45 TRACE EmployeeRepositoryJdbc:151 - Selecting all employees
2018-03-12 13:31:45 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:46 TRACE EmployeeRepositoryJdbc:244 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:31:46 TRACE EmployeeRepositoryJdbc:184 - Getting password hash
2018-03-12 13:31:46 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:47 TRACE EmployeeRepositoryJdbc:245 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:31:47 TRACE EmployeeRepositoryJdbc:205 - Inserting new employee token
2018-03-12 13:31:47 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:31:48 TRACE EmployeeRepositoryJdbc:247 - true
2018-03-12 13:33:47 TRACE EmployeeRepositoryJdbc:32 - Inserting new employee
2018-03-12 13:33:47 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:48 ERROR EmployeeRepositoryJdbc:48 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:46)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:240)
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:240 - false
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:55 - Updating employee
2018-03-12 13:33:48 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:242 - true
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:84 - Selecting employee
2018-03-12 13:33:48 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:243 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:33:48 TRACE EmployeeRepositoryJdbc:118 - Selecting employee
2018-03-12 13:33:48 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:244 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:152 - Selecting all employees
2018-03-12 13:33:49 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:245 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:185 - Getting password hash
2018-03-12 13:33:49 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:246 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:33:49 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:33:49 TRACE EmployeeRepositoryJdbc:248 - true
2018-03-12 13:38:06 TRACE EmployeeRepositoryJdbc:32 - Inserting new employee
2018-03-12 13:38:06 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:09 ERROR EmployeeRepositoryJdbc:48 - Exception thrown while inserting new employee
java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (REIMBURSEMENT_DB.PK_USER) violated

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.insert(EmployeeRepositoryJdbc.java:46)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:251)
2018-03-12 13:38:09 TRACE EmployeeRepositoryJdbc:251 - false
2018-03-12 13:38:09 TRACE EmployeeRepositoryJdbc:55 - Updating employee
2018-03-12 13:38:09 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:10 TRACE EmployeeRepositoryJdbc:253 - true
2018-03-12 13:38:10 TRACE EmployeeRepositoryJdbc:84 - Selecting employee
2018-03-12 13:38:10 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:12 TRACE EmployeeRepositoryJdbc:254 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:38:12 TRACE EmployeeRepositoryJdbc:118 - Selecting employee
2018-03-12 13:38:12 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:13 TRACE EmployeeRepositoryJdbc:255 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:38:13 TRACE EmployeeRepositoryJdbc:152 - Selecting all employees
2018-03-12 13:38:13 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:14 TRACE EmployeeRepositoryJdbc:256 - [Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:38:14 TRACE EmployeeRepositoryJdbc:185 - Getting password hash
2018-03-12 13:38:14 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:15 TRACE EmployeeRepositoryJdbc:257 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:38:15 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:38:15 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:16 TRACE EmployeeRepositoryJdbc:259 - true
2018-03-12 13:38:16 TRACE EmployeeRepositoryJdbc:226 - Inserting deleting employee token
2018-03-12 13:38:16 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:18 ERROR EmployeeRepositoryJdbc:236 - Exception thrown while deleting employee token
java.sql.SQLSyntaxErrorException: ORA-00900: invalid SQL statement

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1075)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3897)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
	at com.revature.repository.EmployeeRepositoryJdbc.deleteEmployeeToken(EmployeeRepositoryJdbc.java:234)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:260)
2018-03-12 13:38:18 TRACE EmployeeRepositoryJdbc:260 - false
2018-03-12 13:38:35 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:38:35 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:37 TRACE EmployeeRepositoryJdbc:259 - true
2018-03-12 13:38:37 TRACE EmployeeRepositoryJdbc:226 - Inserting deleting employee token
2018-03-12 13:38:37 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:38:38 TRACE EmployeeRepositoryJdbc:260 - true
2018-03-12 13:39:00 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:39:00 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:39:01 TRACE EmployeeRepositoryJdbc:259 - true
2018-03-12 13:39:01 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:39:01 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:39:02 TRACE EmployeeRepositoryJdbc:261 - true
2018-03-12 13:39:02 TRACE EmployeeRepositoryJdbc:226 - Inserting deleting employee token
2018-03-12 13:39:02 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:39:03 TRACE EmployeeRepositoryJdbc:262 - true
2018-03-12 13:40:06 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:40:06 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:40:08 TRACE EmployeeRepositoryJdbc:259 - true
2018-03-12 13:40:08 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:40:08 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:40:09 TRACE EmployeeRepositoryJdbc:261 - true
2018-03-12 13:49:50 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:49:50 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:49:51 TRACE EmployeeRepositoryJdbc:294 - true
2018-03-12 13:49:51 TRACE EmployeeRepositoryJdbc:243 - Selecting employee token
2018-03-12 13:49:51 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:49:51 ERROR EmployeeRepositoryJdbc:277 - Exception thrown while selecting employee token
java.sql.SQLSyntaxErrorException: ORA-00904: "PASSWORD_RECOVER"."U_ID": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1017)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:566)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:215)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:58)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:776)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:897)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1034)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3820)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3867)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1502)
	at com.revature.repository.EmployeeRepositoryJdbc.selectEmployeeToken(EmployeeRepositoryJdbc.java:255)
	at com.revature.repository.EmployeeRepositoryJdbc.main(EmployeeRepositoryJdbc.java:295)
2018-03-12 13:49:51 TRACE EmployeeRepositoryJdbc:295 - 
2018-03-12 13:49:51 TRACE EmployeeRepositoryJdbc:226 - Deleting employee token
2018-03-12 13:49:51 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:49:51 TRACE EmployeeRepositoryJdbc:296 - true
2018-03-12 13:50:16 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:50:16 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:16 TRACE EmployeeRepositoryJdbc:294 - true
2018-03-12 13:50:16 TRACE EmployeeRepositoryJdbc:243 - Selecting employee token
2018-03-12 13:50:16 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:17 TRACE EmployeeRepositoryJdbc:295 - EmployeeToken [id=100, token=token, creationDate=2018-03-12T13:50:16.049, requester=Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:50:17 TRACE EmployeeRepositoryJdbc:226 - Deleting employee token
2018-03-12 13:50:17 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:17 TRACE EmployeeRepositoryJdbc:296 - true
2018-03-12 13:50:57 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:50:57 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:58 TRACE EmployeeRepositoryJdbc:294 - true
2018-03-12 13:50:58 TRACE EmployeeRepositoryJdbc:243 - Selecting employee token
2018-03-12 13:50:58 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:58 TRACE EmployeeRepositoryJdbc:295 - EmployeeToken [id=100, token=token, creationDate=2018-03-12T13:50:57.690, requester=Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:50:58 TRACE EmployeeRepositoryJdbc:226 - Deleting employee token
2018-03-12 13:50:58 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:50:58 TRACE EmployeeRepositoryJdbc:296 - true
2018-03-12 13:51:09 TRACE EmployeeRepositoryJdbc:55 - Updating employee
2018-03-12 13:51:09 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:288 - true
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:84 - Selecting employee
2018-03-12 13:51:11 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:289 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:118 - Selecting employee
2018-03-12 13:51:11 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:290 - Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:152 - Selecting all employees
2018-03-12 13:51:11 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:291 - [Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]], Employee [id=1, firstName=PETER, lastName=ALAGNA, username=PALAGNAJR, password=CFE456D83392A087DAF9DF95D5E18366, email=PETER.ALAGNA@REVATURE.COM, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:51:11 TRACE EmployeeRepositoryJdbc:185 - Getting password hash
2018-03-12 13:51:11 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:292 - AE9043C9F2AD12F24C2CEEB10C6A64F0
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:206 - Inserting new employee token
2018-03-12 13:51:12 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:294 - true
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:243 - Selecting employee token
2018-03-12 13:51:12 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:295 - EmployeeToken [id=100, token=token, creationDate=2018-03-12T13:51:12.127, requester=Employee [id=100, firstName=James, lastName=Kempf, username=jamesk4321, password=AE9043C9F2AD12F24C2CEEB10C6A64F0, email=NewExample@gmail.com, userRole=EmployeeRole [id=1, type=EMPLOYEE]]]
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:226 - Deleting employee token
2018-03-12 13:51:12 TRACE ConnectionUtil:14 - Getting connection
2018-03-12 13:51:12 TRACE EmployeeRepositoryJdbc:296 - true
